import type { CentralBankRate, EconomicIndicator } from '../types'

// Static central bank rate data (accurate as of March 2026).
// Update manually or integrate FRED API for live updates.
export const CENTRAL_BANK_RATES: CentralBankRate[] = [
  {
    bank:         'Federal Reserve',
    country:      'United States',
    countryCode:  'US',
    rate:         4.25,
    previousRate: 4.50,
    lastChange:   '2024-12-18',
    nextMeeting:  '2026-03-19',
    trend:        'cutting',
    stance:       'NEUTRAL',
    impliedCuts:  2,
  },
  {
    bank:         'European Central Bank',
    country:      'Eurozone',
    countryCode:  'EU',
    rate:         2.50,
    previousRate: 2.75,
    lastChange:   '2025-01-30',
    nextMeeting:  '2026-03-06',
    trend:        'cutting',
    stance:       'DOVE',
    impliedCuts:  3,
  },
  {
    bank:         'Bank of England',
    country:      'United Kingdom',
    countryCode:  'GB',
    rate:         4.50,
    previousRate: 4.75,
    lastChange:   '2025-02-06',
    nextMeeting:  '2026-03-20',
    trend:        'cutting',
    stance:       'NEUTRAL',
    impliedCuts:  2,
  },
  {
    bank:         'Bank of Japan',
    country:      'Japan',
    countryCode:  'JP',
    rate:         0.50,
    previousRate: 0.25,
    lastChange:   '2025-01-24',
    nextMeeting:  '2026-03-18',
    trend:        'hiking',
    stance:       'HAWK',
    impliedCuts:  -1,
  },
  {
    bank:         "People's Bank of China",
    country:      'China',
    countryCode:  'CN',
    rate:         3.10,
    previousRate: 3.35,
    lastChange:   '2024-10-21',
    nextMeeting:  '2026-04-15',
    trend:        'cutting',
    stance:       'DOVE',
    impliedCuts:  4,
  },
  {
    bank:         'Reserve Bank of Australia',
    country:      'Australia',
    countryCode:  'AU',
    rate:         4.10,
    previousRate: 4.35,
    lastChange:   '2025-02-18',
    nextMeeting:  '2026-04-01',
    trend:        'cutting',
    stance:       'NEUTRAL',
    impliedCuts:  2,
  },
  {
    bank:         'Bank of Canada',
    country:      'Canada',
    countryCode:  'CA',
    rate:         3.00,
    previousRate: 3.25,
    lastChange:   '2025-01-29',
    nextMeeting:  '2026-03-12',
    trend:        'cutting',
    stance:       'DOVE',
    impliedCuts:  3,
  },
  {
    bank:         'Swiss National Bank',
    country:      'Switzerland',
    countryCode:  'CH',
    rate:         0.25,
    previousRate: 0.50,
    lastChange:   '2024-12-12',
    nextMeeting:  '2026-03-20',
    trend:        'cutting',
    stance:       'DOVE',
    impliedCuts:  1,
  },
]

export const KEY_INDICATORS: EconomicIndicator[] = [
  { name: 'US CPI YoY',       value: '2.9%',   change: '+0.1%', positive: false },
  { name: 'US GDP Growth',    value: '2.3%',   change: '-0.4%', positive: false },
  { name: 'Unemployment',     value: '4.1%',   change: '—' },
  { name: 'US 10Y Yield',     value: '4.28%',  change: '-0.05%', positive: true },
  { name: 'US 2Y Yield',      value: '4.01%',  change: '-0.03%', positive: true },
  { name: 'DXY (USD Index)',   value: '103.8',  change: '+0.2%',  positive: false },
  { name: 'VIX',              value: '17.4',   change: '-1.2',   positive: true },
  { name: 'Gold (oz)',        value: '$2,910', change: '+0.6%',  positive: true },
  { name: 'WTI Oil',         value: '$70.1',  change: '-1.1%',  positive: false },
  { name: 'Brent Crude',      value: '$73.8',  change: '-0.9%',  positive: false },
]
